### ISSUE TITLE
Crashes on node 0.12 due to Infinity timeout

### ISSUE THREAD

**Issue by unbracketed** [dpskvn/express-sse#2]
If I change `Infinity` to `0x7FFFFFFF`, code execution continues

```
Server listening on port 8080
RangeError: msecs must be a non-negative finite number
    at Object.exports.enroll (timers.js:160:11)
    at Socket.setTimeout (net.js:337:12)
    at null.<anonymous> (/home/brian/code/react-heroku-log-viewer/node_modules/express-sse/index.js:24:16)
    at Object.sse (/home/brian/code/react-heroku-log-viewer/lib/herokuClientSession.js:34:19)
    at /home/brian/code/react-heroku-log-viewer/lib/server.js:38:11
    at Layer.handle [as handle_request] (/home/brian/code/react-heroku-log-viewer/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/brian/code/react-heroku-log-viewer/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/home/brian/code/react-heroku-log-viewer/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/home/brian/code/react-heroku-log-viewer/node_modules/express/lib/router/layer.js:82:5)
    at /home/brian/code/react-heroku-log-viewer/node_modules/express/lib/router/index.js:267:22
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Expected response to be successful, got 401
    at Request.handleFailure (/home/brian/code/react-heroku-log-viewer/node_modules/heroku-client/lib/request.js:258:9)
    at ConcatStream.directResponse [as cb] (/home/brian/code/react-heroku-log-viewer/node_modules/heroku-client/lib/request.js:167:12)
    at ConcatStream.end (/home/brian/code/react-heroku-log-viewer/node_modules/heroku-client/node_modules/concat-stream/index.js:44:21)
    at IncomingMessage.onend (_stream_readable.js:505:10)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by dpskvn** [comment]
a61fb494 should take care of that.
